name: Trigger auto deployment for merchstore-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/merchstore-containerapp-AutoDeployTrigger-070bc3c2-ef67-43a6-a371-11e09601e527.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MERCHSTORECONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MERCHSTORECONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MERCHSTORECONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: somethingcreativeacr.azurecr.io
          registryUsername: ${{ secrets.MERCHSTORECONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MERCHSTORECONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: merchstore-containerapp
          resourceGroup: SomethingCreative
          imageToBuild: somethingcreativeacr.azurecr.io/merchstore-containerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


